"""initial migration

Revision ID: 370fe51d9e7e
Revises: ae2ca216ba5d
Create Date: 2023-01-21 14:46:32.590960

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '370fe51d9e7e'
down_revision = 'ae2ca216ba5d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('page',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('link',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('page_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['page_id'], ['page.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('link')
    op.drop_table('page')
    # ### end Alembic commands ###
